/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ApiPublicTgWebhookRouteImport } from './routes/api/public/tg/webhook'
import { Route as ApiPublicTgProcessQueueRouteImport } from './routes/api/public/tg/process-queue'
import { Route as ApiPublicTgHealthzRouteImport } from './routes/api/public/tg/healthz'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicTgWebhookRoute = ApiPublicTgWebhookRouteImport.update({
  id: '/api/public/tg/webhook',
  path: '/api/public/tg/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgProcessQueueRoute = ApiPublicTgProcessQueueRouteImport.update({
  id: '/api/public/tg/process-queue',
  path: '/api/public/tg/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgHealthzRoute = ApiPublicTgHealthzRouteImport.update({
  id: '/api/public/tg/healthz',
  path: '/api/public/tg/healthz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTgHealthzRoute: typeof ApiPublicTgHealthzRoute
  ApiPublicTgProcessQueueRoute: typeof ApiPublicTgProcessQueueRoute
  ApiPublicTgWebhookRoute: typeof ApiPublicTgWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/tg/webhook': {
      id: '/api/public/tg/webhook'
      path: '/api/public/tg/webhook'
      fullPath: '/api/public/tg/webhook'
      preLoaderRoute: typeof ApiPublicTgWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/process-queue': {
      id: '/api/public/tg/process-queue'
      path: '/api/public/tg/process-queue'
      fullPath: '/api/public/tg/process-queue'
      preLoaderRoute: typeof ApiPublicTgProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/healthz': {
      id: '/api/public/tg/healthz'
      path: '/api/public/tg/healthz'
      fullPath: '/api/public/tg/healthz'
      preLoaderRoute: typeof ApiPublicTgHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTgHealthzRoute: ApiPublicTgHealthzRoute,
  ApiPublicTgProcessQueueRoute: ApiPublicTgProcessQueueRoute,
  ApiPublicTgWebhookRoute: ApiPublicTgWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
