/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTargetsRouteImport } from './routes/dashboard.targets'
import { Route as DashboardSourcesRouteImport } from './routes/dashboard.sources'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRulesRouteImport } from './routes/dashboard.rules'
import { Route as DashboardQueueRouteImport } from './routes/dashboard.queue'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as ApiPublicTgWebhookRouteImport } from './routes/api/public/tg/webhook'
import { Route as ApiPublicTgProcessQueueRouteImport } from './routes/api/public/tg/process-queue'
import { Route as ApiPublicTgHealthzRouteImport } from './routes/api/public/tg/healthz'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTargetsRoute = DashboardTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesRoute = DashboardRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgWebhookRoute = ApiPublicTgWebhookRouteImport.update({
  id: '/api/public/tg/webhook',
  path: '/api/public/tg/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgProcessQueueRoute = ApiPublicTgProcessQueueRouteImport.update({
  id: '/api/public/tg/process-queue',
  path: '/api/public/tg/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgHealthzRoute = ApiPublicTgHealthzRouteImport.update({
  id: '/api/public/tg/healthz',
  path: '/api/public/tg/healthz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/public/tg/healthz': typeof ApiPublicTgHealthzRoute
  '/api/public/tg/process-queue': typeof ApiPublicTgProcessQueueRoute
  '/api/public/tg/webhook': typeof ApiPublicTgWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard/queue'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/targets'
    | '/dashboard/'
    | '/api/admin/bootstrap'
    | '/api/admin/me'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard/queue'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/targets'
    | '/dashboard'
    | '/api/admin/bootstrap'
    | '/api/admin/me'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard/queue'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/targets'
    | '/dashboard/'
    | '/api/admin/bootstrap'
    | '/api/admin/me'
    | '/api/public/tg/healthz'
    | '/api/public/tg/process-queue'
    | '/api/public/tg/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiPublicTgHealthzRoute: typeof ApiPublicTgHealthzRoute
  ApiPublicTgProcessQueueRoute: typeof ApiPublicTgProcessQueueRoute
  ApiPublicTgWebhookRoute: typeof ApiPublicTgWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/targets': {
      id: '/dashboard/targets'
      path: '/targets'
      fullPath: '/dashboard/targets'
      preLoaderRoute: typeof DashboardTargetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources': {
      id: '/dashboard/sources'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rules': {
      id: '/dashboard/rules'
      path: '/rules'
      fullPath: '/dashboard/rules'
      preLoaderRoute: typeof DashboardRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/webhook': {
      id: '/api/public/tg/webhook'
      path: '/api/public/tg/webhook'
      fullPath: '/api/public/tg/webhook'
      preLoaderRoute: typeof ApiPublicTgWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/process-queue': {
      id: '/api/public/tg/process-queue'
      path: '/api/public/tg/process-queue'
      fullPath: '/api/public/tg/process-queue'
      preLoaderRoute: typeof ApiPublicTgProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/healthz': {
      id: '/api/public/tg/healthz'
      path: '/api/public/tg/healthz'
      fullPath: '/api/public/tg/healthz'
      preLoaderRoute: typeof ApiPublicTgHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardRulesRoute: typeof DashboardRulesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSourcesRoute: typeof DashboardSourcesRoute
  DashboardTargetsRoute: typeof DashboardTargetsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardRulesRoute: DashboardRulesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardTargetsRoute: DashboardTargetsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiPublicTgHealthzRoute: ApiPublicTgHealthzRoute,
  ApiPublicTgProcessQueueRoute: ApiPublicTgProcessQueueRoute,
  ApiPublicTgWebhookRoute: ApiPublicTgWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
